language: scala
scala:
- 2.10.4
jdk:
- openjdk7
branches:
  only:
  - master
after_success:
- sbt publishMasterOnTravis
cache:
  directories:
  - $HOME/.ivy2
notifications:
  hipchat:
    rooms:
      secure: BP7hxRHo+YUKjOpbRsA16247KKb7CTWu/U7wPI1QHjMA9ACNzlDDSyyTyYGKizAQMhlLZi21AIlFEvHXpRyk8FRM+WRrUhUTLQrOelJBmZlCEovPYHS+deFd3Is0/hbmT7gXPOQ2FvVkASCIKfGIiYPYGVwuciqVfwZqnrMZ1mc=
